import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Header from "@/Components/Header";
import SideBar from "@/Components/SideBar";
import "../Components/components.module.css";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <body className={inter.className}>
        <Header  />
        <SideBar />
        {children}
      </body>
    </html>
  );
}
